---
- name: Dev Setup
  hosts: localhost
  vars:
      keys:
      - https://bazel.build/bazel-release.pub.gpg
      - https://pkg.jenkins.io/debian/jenkins.io.key
      - https://apt.releases.hashicorp.com/gpg
      
      repos:
      - deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8
      - deb https://pkg.jenkins.io/debian binary/
      - deb [arch=amd64] https://apt.releases.hashicorp.com {{ docker_version.stdout }} ma
      
      packages:
      - bazel
      - default-jdk
      - jenkins
      - terraform
      
      downloads:
        urls:
        - https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        
        sudo_files:
        - aws/install
      
  tasks:
    - name: add keys
      apt_key:
        state: present
        url: '{{ item }}'
      with_items: '{{ keys }}'
      become: yes
      
    - name: save docker version to variable
      shell: lsb_release -cs
      register: docker_version

    - name: add repositories
      apt_repository: 
        repo: '{{ item }}'
        state: present
      with_items: '{{ repos }}'
      become: yes

    - name: install packages
      apt: 
        name: '{{ packages }}'
        state: latest
        update_cache: yes
      become: yes
      
    - name: download and unzip files
      unarchive:
        src: '{{ item }}'
        dest: .
        copy: no
      with_items: '{{ downloads.urls }}'
      
    - name: run as root downloads
      command: './{{ item }}'
      with_items: '{{ downloads.sudo_files }}'
      become: yes
        
